name: NoDevFee XMRIG Windows
on:
  # Manueel starte
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: check cache
        id: deps
        run: |
          $head = Invoke-Expression 'git ls-remote https://github.com/xmrig/xmrig-deps | select -first 1'
          Write-Host ::set-output name=id::($head.Split("`t"))[0]
      - name: use cache
        uses: actions/cache@v2.1.3
        id: cache
        with:
          path: c:\xmrig-deps\
          key: ${{ runner.os }}-${{ steps.deps.outputs.id }}
      - name: get dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir c:\xmrig-deps
          Invoke-WebRequest -Uri https://github.com/xmrig/xmrig-deps/archive/master.zip -OutFile master.zip
          Expand-Archive -Path master.zip -DestinationPath c:\xmrig-deps\
      - name: build
        run: |
          PowerShell "(Get-Content src/donate.h) -replace 'DonateLevel = 1','DonateLevel = 0' | Set-Content src/donate.h"
          mkdir build
          cd build
          cmake .. -G "Visual Studio 16 2019" -A x64 -DXMRIG_DEPS=c:\xmrig-deps\xmrig-deps-master\msvc2019\x64
          cmake --build . --config Release
      - name: upload windows artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: xmrig-windows
          path: ${{ github.workspace }}\build\Release\xmrig.exe
